### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by iam-alex** [dseight/vscode-disasexpl#9]
Hi Guys,

Great work with this extension.

Can you please tell me the license of the GitHub repository?

I was planning on using the extension for teaching in a lab environment to students online. I wanted to confirm whether I'm allowed to do that or not. 

Thanks!

**Comment by dseight** [comment]
Oh, I'm sorry. It's a bad style to publish something to public without a license, and I totally forgot fix that for a quite long time. Extension is under MIT license, so it's free for use and distribute.

**Comment by dseight** [comment]
License is added to the project with following commit: https://github.com/dseight/vscode-disasexpl/commit/91062b86de0ef83f5492ac7039e361fa9b36e7dc

**Comment by iam-alex** [comment]
Thanks a lot for the confirmation
